/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import model.DanhSachSinhVien;
import model.SinhVien;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public final class QuanLiSinhVienView extends javax.swing.JFrame {

    private final DanhSachSinhVien dssv;
    private ArrayList<SinhVien> dssv_temp;
    private int id;

    /**
     * Creates new form QuanLiSinhVienVIew
     */
    public QuanLiSinhVienView() {
        this.dssv = new DanhSachSinhVien();
        id = 0;
        initComponents();
        //creatDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        del = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        pickKhoa = new javax.swing.JComboBox<>();
        scoreText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        openDB = new javax.swing.JButton();
        save = new javax.swing.JButton();
        sortGender = new javax.swing.JComboBox<>();
        sortKhoa = new javax.swing.JComboBox<>();
        searchMSSV = new javax.swing.JTextField();
        searchName = new javax.swing.JTextField();
        sortScores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ Và Tên", "Giới tính", "Năm sinh", "Khoa", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAlignmentX(1.0F);
        jTable1.setAlignmentY(1.0F);
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        edit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edit.setText("Sửa thông tin");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        del.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        del.setText("Xóa sinh viên");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ và tên");

        nameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Giới tính");

        sex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Năm sinh");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Khoa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Điểm");

        add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add.setText("Thêm SV");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        pickKhoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pickKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kỹ thuật phần mềm", "Marketing", "Thiết kế đồ họa", "Ngôn ngữ Anh", "Kinh doanh quốc tế" }));
        pickKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickKhoaActionPerformed(evt);
            }
        });

        scoreText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scoreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        scoreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Nhập thông tin");

        openDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openDB.setText("Cập nhật DB");
        openDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nameText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pickKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openDB, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pickKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        save.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        save.setText("Lưu file");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        sortGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giới tính", "Nam", "Nữ" }));
        sortGender.setName("Giới tính"); // NOI18N
        sortGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortGenderActionPerformed(evt);
            }
        });

        sortKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa", "Kỹ thuật phần mềm", "Marketing", "Thiết kế đồ họa", "Ngôn ngữ Anh", "Kinh doanh quốc tế" }));
        sortKhoa.setName("Khoa"); // NOI18N
        sortKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortKhoaActionPerformed(evt);
            }
        });

        searchMSSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMSSVActionPerformed(evt);
            }
        });

        searchName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameActionPerformed(evt);
            }
        });

        sortScores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortScores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp", "Cao -> thấp", "Thấp -> cao" }));
        sortScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortScoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(del)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(searchMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sortGender, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(sortKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(sortScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del)
                    .addComponent(edit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(save))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortGender)
                    .addComponent(searchMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        del.getAccessibleContext().setAccessibleName("timTen");
        resetButton.getAccessibleContext().setAccessibleName("timKhoa");

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void creatDatabase() {
//        SinhVien sv1 = new SinhVien(1, "Lâm Quốc Nhân", "Nam", "01/01/2002", "Kỹ thuật phần mềm", 9);
//        SinhVien sv2 = new SinhVien(2, "Nguyễn Hoàng Nguyên", "Nam", "02/02/2002", "Kỹ thuật phần mềm", 6);
//        SinhVien sv3 = new SinhVien(3, "Nguyễn Trần Thanh Duy", "Nữ", "03/03/2002", "Thiết kế đồ họa", 5);
//        SinhVien sv4 = new SinhVien(4, "Văn Tuấn Kiệt", "Nam", "04/04/2002", "Thiết kế đồ họa", 2);
//        SinhVien sv5 = new SinhVien(5, "Văn Tuấn Kiệt", "Nữ", "05/05/2002", "Kỹ thuật phần mềm", 3);
//        SinhVien sv6 = new SinhVien(6, "Văn Tuấn Kiệt", "Nữ", "06/06/2002", "Thiết kế đồ họa", 8);
//        SinhVien sv7 = new SinhVien(7, "Văn Tuấn Kiệt", "Nữ", "07/07/2002", "Thiết kế đồ họa", 1);
//        dssv.insert(sv1);
//        dssv.insert(sv2);
//        dssv.insert(sv3);
//        dssv.insert(sv4);
//        dssv.insert(sv5);
//        dssv.insert(sv6);
//        dssv.insert(sv7);
//        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
//        for (SinhVien student : dssv.getDssv()) {
//            defaultTableModel.addRow(new Object[]{
//                student.getMssv(),
//                student.getName(),
//                student.getGender(),
//                student.getDate(),
//                student.getKhoa(),
//                student.getDiem()
//            });
//        }
//    }
    private void reset() {
        nameText.setText("");
        dateText.setDate(null);
        scoreText.setText("");
        jTable1.clearSelection();

    }

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed

        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        int row_seclected = jTable1.getSelectedRow();
        Object[] options = {"Yes", "No"};
        try {
            int mssv = (int) defaultTableModel.getValueAt(row_seclected, 0);
            int luaChon = JOptionPane.showOptionDialog(this,
                    "Bạn có muốn xóa sinh viên này ?",
                    "Xác nhận",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, //do not use a custom Icon
                    options, //the titles of buttons
                    options[0]); //default button title
            if (luaChon == JOptionPane.YES_OPTION) {
                for (int i = 0; i < dssv.getSize(); i++) {
                    if (dssv.getmssv(i) == mssv) {
                        dssv.del(dssv.getSV(i));
                        break;
                    }
                }
                defaultTableModel.removeRow(row_seclected);
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_delActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        searchMSSV.setText("");
        searchName.setText("");
        sortGender.setSelectedItem("Giới tính");
        sortKhoa.setSelectedItem("Khoa");
        sortScores.setSelectedItem("Sắp xếp");
        defaultTableModel.setRowCount(0);
        showData();
        reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

        Object[] options = {"Yes", "No"};
        int luaChon = JOptionPane.showOptionDialog(this,
                "Bạn có muốn cập nhật thông tin sinh viên này ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        try {
            if (luaChon == JOptionPane.YES_OPTION) {
                DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
                int row_seclected = jTable1.getSelectedRow();
                int mssv = (int) defaultTableModel.getValueAt(row_seclected, 0);
                String name = nameText.getText();
                for (char c : name.toCharArray()) {
                    if (Character.isDigit(c)) {
                        JOptionPane.showMessageDialog(this, "Họ và tên không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        reset();
                        return;
                    }
                }
                String gender = sex.getSelectedItem().toString();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date date1 = dateText.getDate();
                String date = format.format(date1);
                String khoa = pickKhoa.getSelectedItem().toString();
                float diem = Float.parseFloat(scoreText.getText());
                if (diem < 0 || diem > 10) {
                    JOptionPane.showMessageDialog(this, "Điểm số không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    reset();
                    return;
                }
                for (int i = 0; i < dssv.getSize(); i++) {
                    if (dssv.getmssv(i) == mssv) {
                        dssv.edit(i, mssv, name, gender, date, khoa, diem);
                        defaultTableModel.setValueAt(mssv, row_seclected, 0);
                        defaultTableModel.setValueAt(name, row_seclected, 1);
                        defaultTableModel.setValueAt(gender, row_seclected, 2);
                        defaultTableModel.setValueAt(date, row_seclected, 3);
                        defaultTableModel.setValueAt(khoa, row_seclected, 4);
                        defaultTableModel.setValueAt(diem, row_seclected, 5);
                        break;
                    }
                }
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thể sửa thông tin \n Vui lòng kiểm tra lại dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                String filePath = fileChooser.getSelectedFile().getPath();
                try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
                    for (int i = 0; i < dssv.getSize(); i++) {
                        String data = dssv.getSV(i).toString();
                        writer.write(data); // Ghi dữ liệu vào tệp tin
                    }
                }
                JOptionPane.showMessageDialog(null, "Dữ liệu đã được ghi vào tệp tin.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi ghi dữ liệu vào tệp tin: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn đã hủy chọn tệp tin.");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        int row_seclected = jTable1.getSelectedRow();
        Object valueAt = defaultTableModel.getValueAt(row_seclected, 1);
        nameText.setText((String) valueAt);
        valueAt = defaultTableModel.getValueAt(row_seclected, 2);
        sex.setSelectedItem((String) valueAt);
        valueAt = defaultTableModel.getValueAt(row_seclected, 3);
        String date1 = (String) valueAt;
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date date = format.parse(date1);
            dateText.setDate(date);
        } catch (ParseException e) {
        }
        valueAt = defaultTableModel.getValueAt(row_seclected, 4);
        pickKhoa.setSelectedItem((String) valueAt);
        valueAt = defaultTableModel.getValueAt(row_seclected, 5);
        scoreText.setText(valueAt.toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void sortGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortGenderActionPerformed

        searchMSSV.setText("");
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        String genderBox = sortGender.getSelectedItem().toString();
        String khoaBox = sortKhoa.getSelectedItem().toString();
        String nameTemp = searchName.getText().toLowerCase();
        String sort = this.sortScores.getSelectedItem().toString();
        switch (sort) {
            case "Cao -> thấp" ->
                dssv.sortCaoDenThap();
            case "Thấp -> cao" ->
                dssv.sortThapdenCao();
            default ->
                dssv.resetSort();
        }
        defaultTableModel.setRowCount(0);
        dssv_temp = new ArrayList<>();
        for (int i = 0; i < dssv.getSize(); i++) {
            boolean isGenderMatched = genderBox.equals("Giới tính") || dssv.getGender(i).equals(genderBox);
            boolean isKhoaMatched = khoaBox.equals("Khoa") || dssv.getKhoa(i).equals(khoaBox);
            boolean isNameMatched = nameTemp.isEmpty() || dssv.getSV(i).getName().toLowerCase().contains(nameTemp);
            if (isGenderMatched && isKhoaMatched && isNameMatched) {
                dssv_temp.add(dssv.getSV(i));
            }
        }
        for (SinhVien student : dssv_temp) {
            defaultTableModel.addRow(new Object[]{
                student.getMssv(),
                student.getName(),
                student.getGender(),
                student.getDate(),
                student.getKhoa(),
                student.getDiem()
            });
        }
    }//GEN-LAST:event_sortGenderActionPerformed

    private void sortKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortKhoaActionPerformed

        searchMSSV.setText("");
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        String genderBox = sortGender.getSelectedItem().toString();
        String khoaBox = sortKhoa.getSelectedItem().toString();
        String nameTemp = searchName.getText().toLowerCase();
        String sort = this.sortScores.getSelectedItem().toString();
        switch (sort) {
            case "Cao -> thấp" ->
                dssv.sortCaoDenThap();
            case "Thấp -> cao" ->
                dssv.sortThapdenCao();
            default ->
                dssv.resetSort();
        }
        defaultTableModel.setRowCount(0);
        dssv_temp = new ArrayList<>();
        for (int i = 0; i < dssv.getSize(); i++) {
            boolean isGenderMatched = genderBox.equals("Giới tính") || dssv.getGender(i).equals(genderBox);
            boolean isKhoaMatched = khoaBox.equals("Khoa") || dssv.getKhoa(i).equals(khoaBox);
            boolean isNameMatched = nameTemp.isEmpty() || dssv.getSV(i).getName().toLowerCase().contains(nameTemp);
            if (isGenderMatched && isKhoaMatched && isNameMatched) {
                dssv_temp.add(dssv.getSV(i));
            }
        }
        for (SinhVien student : dssv_temp) {
            defaultTableModel.addRow(new Object[]{
                student.getMssv(),
                student.getName(),
                student.getGender(),
                student.getDate(),
                student.getKhoa(),
                student.getDiem()
            });
        }
    }//GEN-LAST:event_sortKhoaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //reset();
    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        reset();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void scoreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreTextActionPerformed

    private void pickKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickKhoaActionPerformed

    }//GEN-LAST:event_pickKhoaActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
            String name = nameText.getText();
            for (char c : name.toCharArray()) {
                if (Character.isDigit(c)) {
                    JOptionPane.showMessageDialog(this, "Họ và tên không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    reset();
                    return;
                }
            }
            String gender = sex.getSelectedItem().toString();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date date = dateText.getDate();
            String formattedDate = format.format(date);
            float diem = Float.parseFloat(scoreText.getText());
            if (diem < 0 || diem > 10) {
                JOptionPane.showMessageDialog(this, "Điểm số không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                reset();
                return;
            }
            String nganh = pickKhoa.getSelectedItem().toString();
            SinhVien sinhVien = new SinhVien(++id, name, gender, formattedDate, nganh, diem);
            dssv.insert(sinhVien);
            dssv_temp = dssv.getDssv();
            defaultTableModel.addRow(new Object[]{
                id, name, gender, formattedDate, nganh, diem
            });
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại dữ liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            reset();

        }
    }//GEN-LAST:event_addActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameActionPerformed

        searchMSSV.setText("");
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        String genderBox = sortGender.getSelectedItem().toString();
        String khoaBox = sortKhoa.getSelectedItem().toString();
        String nameTemp = searchName.getText().toLowerCase();
        String sort = this.sortScores.getSelectedItem().toString();
        switch (sort) {
            case "Cao -> thấp" ->
                dssv.sortCaoDenThap();
            case "Thấp -> cao" ->
                dssv.sortThapdenCao();
            default ->
                dssv.resetSort();
        }
        defaultTableModel.setRowCount(0);
        dssv_temp = new ArrayList<>();
        for (int i = 0; i < dssv.getSize(); i++) {
            boolean isGenderMatched = genderBox.equals("Giới tính") || dssv.getGender(i).equals(genderBox);
            boolean isKhoaMatched = khoaBox.equals("Khoa") || dssv.getKhoa(i).equals(khoaBox);
            boolean isNameMatched = nameTemp.isEmpty() || dssv.getSV(i).getName().toLowerCase().contains(nameTemp);

            if (isGenderMatched && isKhoaMatched && isNameMatched) {
                dssv_temp.add(dssv.getSV(i));
            }
        }
        for (SinhVien student : dssv_temp) {
            defaultTableModel.addRow(new Object[]{
                student.getMssv(),
                student.getName(),
                student.getGender(),
                student.getDate(),
                student.getKhoa(),
                student.getDiem()
            });
        }
    }//GEN-LAST:event_searchNameActionPerformed

    private void showData() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        for (SinhVien student : dssv.getDssv()) {
            defaultTableModel.addRow(new Object[]{
                student.getMssv(),
                student.getName(),
                student.getGender(),
                student.getDate(),
                student.getKhoa(),
                student.getDiem()
            });
        }
    }
    private void searchMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMSSVActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        String text = searchMSSV.getText();
        if (!text.isEmpty()) {
            try {
                int x = Integer.parseInt(text);
                if (!sortGender.getSelectedItem().equals("Giới tính")) {
                    sortGender.setSelectedItem("Giới tính");
                }
                if (!sortKhoa.getSelectedItem().equals("Khoa")) {
                    sortKhoa.setSelectedItem("Khoa");
                }
                if (!sortScores.getSelectedItem().equals("Sắp xếp")) {
                    sortScores.setSelectedItem("Sắp xếp");
                }
                searchName.setText("");
                searchMSSV.setText(text);
                defaultTableModel.setRowCount(0);
                for (int i = 0; i < dssv.getSize(); i++) {
                    if (dssv.getmssv(i) == x) {
                        defaultTableModel.addRow(new Object[]{
                            dssv.getmssv(i),
                            dssv.getName(i),
                            dssv.getGender(i),
                            dssv.getDate(i),
                            dssv.getKhoa(i),
                            dssv.getScores(i)
                        });
                        break;
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            defaultTableModel.setRowCount(0);
            showData();
        }
    }//GEN-LAST:event_searchMSSVActionPerformed

    private void dateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextMouseClicked

    }//GEN-LAST:event_dateTextMouseClicked

    private void sortScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortScoresActionPerformed

        if (!searchMSSV.getText().isEmpty()) {
            return;
        }
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        String genderBox = sortGender.getSelectedItem().toString();
        String khoaBox = sortKhoa.getSelectedItem().toString();
        String nameTemp = searchName.getText().toLowerCase();
        String sort = this.sortScores.getSelectedItem().toString();
        switch (sort) {
            case "Cao -> thấp" ->
                dssv.sortCaoDenThap();
            case "Thấp -> cao" ->
                dssv.sortThapdenCao();
            default ->
                dssv.resetSort();
        }
        defaultTableModel.setRowCount(0);
        dssv_temp = new ArrayList<>();
        for (int i = 0; i < dssv.getSize(); i++) {
            boolean isGenderMatched = genderBox.equals("Giới tính") || dssv.getGender(i).equals(genderBox);
            boolean isKhoaMatched = khoaBox.equals("Khoa") || dssv.getKhoa(i).equals(khoaBox);
            boolean isNameMatched = nameTemp.isEmpty() || dssv.getSV(i).getName().toLowerCase().contains(nameTemp);
            if (isGenderMatched && isKhoaMatched && isNameMatched) {
                dssv_temp.add(dssv.getSV(i));
            }
        }
        for (SinhVien student : dssv_temp) {
            defaultTableModel.addRow(new Object[]{
                student.getMssv(),
                student.getName(),
                student.getGender(),
                student.getDate(),
                student.getKhoa(),
                student.getDiem()
            });
        }
    }//GEN-LAST:event_sortScoresActionPerformed

    private void openDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDBActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                String line;
                while ((line = reader.readLine()) != null) {

                    String[] infor = line.split(",");
                    int mssv = Integer.parseInt(infor[0]);
                    String name = infor[1];
                    String gender = infor[2];
                    String date = infor[3];
                    String khoa = infor[4];
                    float diem = Float.parseFloat(infor[5]);
                    SinhVien sv = new SinhVien(mssv, name, gender, date, khoa, diem);
                    dssv.insert(sv);
                    ++id;
                }
                DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
                for (SinhVien student : dssv.getDssv()) {
                    defaultTableModel.addRow(new Object[]{
                        student.getMssv(),
                        student.getName(),
                        student.getGender(),
                        student.getDate(),
                        student.getKhoa(),
                        student.getDiem()
                    });
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuanLiSinhVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton openDB;
    private javax.swing.JComboBox<String> pickKhoa;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton save;
    private javax.swing.JTextField scoreText;
    private javax.swing.JTextField searchMSSV;
    private javax.swing.JTextField searchName;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JComboBox<String> sortGender;
    private javax.swing.JComboBox<String> sortKhoa;
    private javax.swing.JComboBox<String> sortScores;
    // End of variables declaration//GEN-END:variables

}
